source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!

pod 'PPRevealSideViewController', '~> 1.2.0'
pod 'AFNetworking', '~> 2.4.1'
pod 'TMCache', '~> 1.2.2'
pod 'RSCategories', '~> 0.1'
pod 'NYXImagesKit', '~> 2.3'
pod 'NSTimer-Blocks'
pod 'NSDate-ServerDate'
pod 'Reachability', '~> 3.1.1'
pod 'iRate', '~> 1.11'
pod 'MBProgressHUD', '~> 0.9'
pod 'pop', '~> 1.0.7'
pod 'Mantle', '~> 1.5.1'
pod 'FLEX', '~> 1.1.1'
pod 'PureLayout', '~> 2.0.1'
pod 'SDWebImage', '~> 3.7.1'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
pod 'DateTools', '~> 1.4.3'
pod 'uicontrol-blocks', '~> 1.1.0'
pod 'ObjectiveSugar', '~> 1.1.0'
pod 'JTObjectMapping', '~> 1.1.2'
pod 'PunchScrollView', '~> 1.1.0'
pod 'MMDrawerController', '~> 0.5.7'
pod 'UIImage-Helpers', '~> 0.0.3'
pod 'UIImage+Additions', '~> 1.2.0'
pod 'INTULocationManager', '~> 1.2.0'
pod 'SWTableViewCell', '~> 0.3.6'
pod 'SMPageControl', '~> 1.2' 
pod 'AFNetworkingLogger', :git => 'https://github.com/stanislaw/AFNetworkingLogger'

